wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      3:
      - 2
      4: 3.7.10
      5: 0.10.24
      8:
      - 5
