wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.10
      5: 0.10.24
      8:
      - 5
learning_rate:
  desc: null
  value: 5.0e-05
use_experts:
  desc: null
  value: false
